import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function FirstPost() {
  const { data: session, status } = useSession();
  console.log(session);
  // If no session exists, display access denied message
  if (!session) {
    return (
      <>
        <Head>
          <title>Acerca de</title>
        </Head>
        <main>
          <h1>Acceso denegado</h1>
        </main>
      </>
    )
  }

  return (
    <>
      <Head>
        <title>Acerca de</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Acerca de nosotros</h1>
        <Link href="/">Inicio</Link>
      </main>
    </>
  )
}