import React from 'react';//se puede poner y no, ya que estamos trabajando con react
import Typography from '@mui/material/Typography';
import { Container, Grid, Paper, Chip, TextField, FormControl, InputLabel, Select, MenuItem, Autocomplete, NativeSelect, Breadcrumbs } from '@mui/material';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import apiClient from 'apiClient'
import {useRouter} from 'next/router';

export default function Products(){
    const router = useRouter();
    const [components,setComponents] = useState([])
    //console.log(router)

    useEffect(() => {
        if(router.query.slug){
        apiClient.get(`/api/components/${router.query.slug}`)
        .then((response) => {
            //console.log(response.data)
            //alert('si conecto');
            setComponents(response.data)
        })
        .catch((error) => {
            alert("Error al visualizar el componente, intente más tarde")
        });
        }
    }, [router]);

    console.log(components)
    return (
        <>
        <Head>
            <title>Componentes</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>


        <Paper>
        <h1>Informacion del componente</h1>
        
        <Typography>Nombre del componente: {components?.name}</Typography>
        <Typography>Precio: {components?.price}</Typography>
        
    <Container>
    </Container>
    </Paper>

</>
    )
}